### ISSUE TITLE
What’s the exact use of "support layers"?

### ISSUE THREAD

**Issue by twardoch** [LettError/mutatorSans#13]
The font contains "support layers", e.g. 

```
    <array>
      <string>foreground</string>
      <string>glyphs</string>
    </array>
    <array>
      <string>support</string>
      <string>glyphs.support</string>
    </array>
    <array>
      <string>support.crossbar</string>
      <string>glyphs.support.crossbar</string>
    </array>
```
The [UFO 3](http://unifiedfontobject.org/versions/ufo3/layercontents.plist/) spec discusses the `public.` suffixes, but I cannot 
find references to `support` — is this some standardized prefix where those layers need to be treated somehow specially, or is this a normal glyph layer?

**Comment by LettError** [comment]
It is just a layer named "support". It provides glyph geometry to a specific point in the designspace. It does not have to contain all glyphs.
