### ISSUE TITLE
This Needs More Glyphs

### ISSUE THREAD

**Issue by Bronnel721** [LettError/mutatorSans#16]
I would like to use this for my brand, but add numbers, more symbols, numerators and denominators, accents (including Latin Extended-A) and lowercases that actually look like lowercases so I can use this.

**Comment by justvanrossum** [comment]
This is a free test font for testing purposes, generously published as open source by its maker. It is what it is until you contribute, or hire someone to contribute on your behalf.

**Comment by Bronnel721** [comment]
But I don't want to do that.

**Comment by Bronnel721** [comment]
It's me from the future! I have to let you know, do you think Google Fonts can do this?

**Comment by LettError** [comment]
@MarcoMahone what is your question?

**Comment by Bronnel721** [comment]
Are you going make this font have a complete character set?

**Comment by kenmcd** [comment]
> Are you going make this font have a complete character set?

Based on this "issue" and your other "I want this" posts in other font repositories, I will attempt to make this clear to you.
**No.**
 In case that is not clear enough ... you may want to READ the About info.

> Source font data for a small 2 dimensional designspace, for testing all sorts of variable math and making it not look stupid. 

What that means is that this is a font for TESTING stuff.
This is not a released font family which is in active development.
And there are no plans for active development, and there never was.
There are not going to be any additional characters, or features, or anything else.

This is not a commercial font you paid for which _may_ be interested in your demands.
If you want changes in this font - _pay someone_ to make the changes.
The people who made this _testing font_ **generously** made it available as open source.
So you have the benefit of their knowledge and many hours of work for free.
If you want to continue development based on this work, it is your responsibility.

Hopefully that is that is now clear enough for you.

**Comment by Bronnel721** [comment]
Yes that is that is clear enough for me but
1. I can only use fontforge and it doesn't care about variable fonts.
2. I don't wanna pay.
3. Fontforge is super annoying and that's the only program I can afford.
Also if you want me to stop, I will. But I don't really want to add gylphs myself and I'm not that good at pull requests.

**Comment by justvanrossum** [comment]
1. You want people to do free work
2. People don't want to do your work for free
3. The end

**Comment by Bronnel721** [comment]
@kenmcd, look at this: https://github.com/Etcetera-Type-Co/Anybody/issues/1 https://github.com/Etcetera-Type-Co/Anybody/issues/1 https://github.com/Etcetera-Type-Co/Trispace/issues/1. Don't you see? I'm not the only person that writes these "issues". And did you see me saying that I don't know how to take pull requests?

**Comment by kenmcd** [comment]
> And did you see me saying that I don't know how to take pull requests?

Oh, "pull requests" brings back good memories.
My grandfather used to say "pull my finger"
That's when the magic happened.

**Comment by Bronnel721** [comment]
@kenmcd Why do you have to be so sarcastic? Also what about these: Etcetera-Type-Co/Anybody#1 Etcetera-Type-Co/Anybody#1 Etcetera-Type-Co/Trispace#1

**Comment by kenmcd** [comment]
> Also what about these: [Etcetera-Type-Co/Anybody#1](https://github.com/Etcetera-Type-Co/Anybody/issues/1) [Etcetera-Type-Co/Anybody#1](https://github.com/Etcetera-Type-Co/Anybody/issues/1) [Etcetera-Type-Co/Trispace#1](https://github.com/Etcetera-Type-Co/Trispace/issues/1)

OK, if you insist ...
Oh look, another completely self-centered person with no manners and zero common sense making clueless demands. 
Have no idea why anyone would point to those as some sort of justification.
Done here.

**Comment by Bronnel721** [comment]
@kenmcd It's because I'm not the only person that writes these "issues". There's tons of other people doing it like for example this one: https://github.com/mjlagattuta/Hepta-Slab/issues/12. Not only are there other people doing this, but this person also got three likes.

**Comment by Bronnel721** [comment]
@kenmcd, reply to me. Look at this: mjlagattuta/Hepta-Slab#12. Don't you understand?
